name: Run Maven Tests and Deploy Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Test
        run: |
          mvn clean test
          mvn allure:report

      - name: Generate Allure HTML report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Debug - List Allure report contents
        run: |
          Get-ChildItem -Path "target/allure-report" -Recurse
        shell: pwsh

      - name: Prepare GitHub Pages directory
        run: |
          $pagesDir = "gh-pages"
          New-Item -Path $pagesDir -ItemType Directory -Force
          Copy-Item -Path "target/allure-report/*" -Destination $pagesDir -Recurse -Force
        shell: pwsh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages

      - name: Output Allure Report URL
        run: |
          echo "Allure report is published to https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
        shell: bash