name: Run Maven Tests and Deploy Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create Log directory
        run: |
          New-Item -Path "src/test/resources/Log" -ItemType Directory -Force
        shell: pwsh

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~\.m2\repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test with Maven
        run: |
          mvn clean test
          mvn allure:report
        shell: pwsh

      - name: Debug - List contents of target directory
        run: |
          Get-ChildItem -Path "target" -Recurse | Select-Object FullName
        shell: pwsh

      - name: Debug - Check Allure results existence
        run: |
          if (Test-Path "target/allure-results") {
            Write-Host "Allure results directory found."
            Get-ChildItem -Path "target/allure-results" -Recurse | Select-Object FullName
          } else {
            Write-Host "Allure results directory NOT found."
          }
        shell: pwsh

      - name: Upload Log Files
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: src/test/resources/Log/*.log

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: Allure-Results
          path: target/allure-results

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure HTML report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Debug - Check Allure report location
        run: |
          if (Test-Path "target/allure-report") {
            Write-Host "Allure HTML report found in target/allure-report"
            Get-ChildItem -Path "target/allure-report" -Recurse | Select-Object FullName
          } else {
            Write-Host "Allure HTML report NOT found in target/allure-report"
          }
        shell: pwsh

      - name: Debug - Verify Node.js and Allure CLI
        run: |
          node --version
          allure --version

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Output Allure Report URL
        if: always()
        run: |
          echo "Allure report is published to https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        shell: bash