name: Run Maven Tests

on:
  push:
    branches:
      - master  # Change this to your default branch if necessary
  pull_request:
    branches:
      - master  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the JDK version your project uses
          distribution: 'temurin'  # Use 'temurin', 'adopt', or 'zulu'

      - name: Create Log directory (Windows)
        run: |
          if (-Not (Test-Path -Path "src/test/resources/Log")) { New-Item -Path "src/test/resources/Log" -ItemType Directory }
        shell: pwsh  # Use PowerShell as the shell on Windows

      - name: Build with Maven
        run: mvn clean  # Clean the project

      - name: Run API tests
        run: mvn test  # Run the tests

      - name: Upload Log Files
        uses: actions/upload-artifact@v3  # Ensure you're using the latest version
        with:
          name: test-logs
          path: src/test/resources/Log/*.log  # Adjust the path if needed
