name: Run Maven Tests and Publish Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create Log directory (Windows)
        run: |
          if (-Not (Test-Path -Path "src/test/resources/Log")) { New-Item -Path "src/test/resources/Log" -ItemType Directory }
        shell: pwsh

      - name: Build with Maven
        run: mvn clean

      - name: Run API tests
        run: mvn test

      - name: Upload Log Files
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: src/test/resources/Log/*.log

      - name: Generate Allure Report
        run: mvn allure:report

      - name: List contents of target directory
        run: ls -R target
        shell: bash

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: Allure-Results
          path: target/allure-results

      - name: Check if Allure report exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "target/site/allure-maven-plugin/index.html"

      - name: Deploy Allure Report to GitHub Pages
        if: steps.check_files.outputs.files_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages

      - name: Output Allure Report URL
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "Allure report is published to https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
        shell: bash