name: Run Maven Tests

on:
  push:
    branches:
      - master  # Change this to your default branch if necessary
  pull_request:
    branches:
      - master  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the JDK version your project uses
          distribution: 'temurin'  # You can use 'adopt' or 'zulu' as alternatives

      - name: Build with Maven
        run: mvn clean install  # You can change this to 'mvn test' if you only want to run tests

      - name: Run API tests
        run: mvn test
